.TH "Simp_Compression::Simp_Compression_Func" 3 "Version 0.0.1" "Simp_Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Simp_Compression::Simp_Compression_Func \- 包含压缩和解压缩函数的对象。  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <include\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "std::function< bool(std::string &&, bool, std::string &&, bool)> \fBGeneCompression\fP = \fBGene_Compression\fP"
.br
.ti -1c
.RI "std::function< bool(std::string &&, bool, std::string &&, bool)> \fBGeneDecompression\fP = \fBGene_Decompression\fP"
.br
.in -1c
.SH "详细描述"
.PP 
包含压缩和解压缩函数的对象。 

.SH "作者"
.PP 
由 Doyxgen 通过分析 Simp_Compression 的 源代码自动生成\&.
